@hackathon
Feature: Test impl - Firefox

Scenario: Firefox Buy latest console camera and pre order game

Given I'm using browser "firefox"
And Navigate to url "http://www.amazon.com"
And Search for "PlayStation 4 Slim 1TB Console" product
And Select first product in results
And Add Item to shopping cart
And Search for "PlayStation 4 camera" product
And Select first product in results
And Search for "just dance 2018 playstation 4" product
And Select first product in results
And Add Item to shopping cart
And View shopping cart
And Proceed to checkout

# Generated by Cucable

