@hackathon
Feature: Test impl - Safari

Scenario: Safari Buy latest console camera and pre order game

Given I'm using browser "safari"
And Navigate to url "http://www.amazon.com"
And Search for "PlayStation 4 Slim 1TB Console" product
And Merchant should be verified by "Amazon.com"
And Search for "PlayStation 4 camera" product
And Search for "just dance 2018 playstation 4" product

# Generated by Cucable

