package parallel.runners;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;

/**
 * Test Runner for cucumber scenarios
 */
@RunWith(Cucumber.class)
@CucumberOptions(
        monochrome = false,
        tags = {"~@ignore"},
        features = "classpath:parallel/features/Amazon_scenario001_run001_IT.feature",
        glue = {"com.workable.hackathon.steps"},
        plugin = {"com.workable.hackathon.common.reporters.AllureReporter",
        "com.epam.reportportal.cucumber.StepReporter",
                "json", "json:target/cucumber-report/[].json"}
)
public class Amazon_scenario001_run001_IT {
}
// Generated by Cucable

